// Import stylesheets
import './style.css';

// Write Javascript code!
const appDiv = document.getElementById('app');
appDiv.innerHTML = `<h1>JS Starter</h1>`;

(function download(data, extension){
	 data =  `
{\rtf1\ansi\deff0 
{\fonttbl
{\f0 \fArial Arial;}
{\f1 Times;}
{\f2 Courier New;}
{\f3 \fCalibri Calibri;}
}
{\colortbl
;
\red0\green0\blue0;
\red255\green255\blue255;
\red255\green0\blue0;
}
{\info
{\title RTF Template}
{\doccomm Generated by Oracle BI Publisher 12.2.1.4.0}
}
\formshade\viewkind1\viewbksp1\uc1\dntblnsbdb
\paperw12240\paperh15840\margt140\margb180\margl140\margr140
\headery140\footery180{\header \pard\itap0\qc\sl259\slmult1\lin120\rin120\tqc\tx4788\tqr\tx9468 {\f0\fs20\cf1 WITS 3}{\f0\fs20\cf1\par}
\trowd
\trleft131
\clvertalb\clcbpat2\clbrdrb\brdrs\brdrw30\brdrcf1
\cellx3651
\clvertalb\clcbpat2\clbrdrb\brdrs\brdrw30\brdrcf1
\cellx8243
\clvertalb\clcbpat2\clbrdrb\brdrs\brdrw30\brdrcf1
\cellx11840
\pard\intbl\sl-289\slmult0\lin108\rin108\tx576\tqc\tx5615\tqr\tx11016 {\f0\fs20\cf1 02/11/2020}{\f0\fs20\cf1\cell}
\pard\intbl\qc\sl-289\slmult0\lin108\rin108\tx576\tqc\tx5615\tqr\tx11016 {\f0\fs20\b\cf1 Troubles by Trouble Code}{\f0\fs20\b\cf1\cell}
\pard\intbl\qr\sl-289\slmult0\lin108\rin108\tx576\tqc\tx5615\tqr\tx11016 {\f0\fs20\cf1 15:02:48}{\f0\fs20\cf1\cell}
\trowd
\trleft131
\clvertalb\clcbpat2\clbrdrb\brdrs\brdrw30\brdrcf1
\cellx3651
\clvertalb\clcbpat2\clbrdrb\brdrs\brdrw30\brdrcf1
\cellx8243
\clvertalb\clcbpat2\clbrdrb\brdrs\brdrw30\brdrcf1
\cellx11840
\row	
\pard\itap0\sl259\slmult1\sa160\lin120\rin120\tqc\tx4788\tqr\tx9468 {\f3\fs22\cf1\par}
}
{\footer \pard\itap0\qc\sl259\slmult1\sa160\lin120\rin120\tqc\tx4788\tqr\tx9468 {\f3\fs22\cf1\par}
\trowd
\trleft12
\clcbpat2\clbrdrt\brdrs\brdrw20\brdrcf1
\cellx1938
\clcbpat2\clbrdrt\brdrs\brdrw20\brdrcf1
\cellx9756
\clcbpat2\clbrdrt\brdrs\brdrw20\brdrcf1
\cellx11840
\pard\intbl\sl-188\slmult0\lin108\rin218 {\f0\fs16\cf1 Service@once}{\f0\fs16\cf1\cell}
\pard\intbl\qc\sl0\lin108\rin108\tqc\tx4788\tqr\tx9468 {\f0\fs16\cf1 Not for use or disclosure outside the Washington Interagency Telecommunications System }\line {\f0\fs16\cf1 or Verizon Federal except under written agreement.}{\f0\fs16\cf1\par}
\pard\intbl\qc\sl0\lin108\rin108\tqc\tx4788\tqr\tx9468 \cell
\pard\intbl\qr\sl-188\slmult0\lin108\rin218 {\f0\fs16\cf1 TRB009 - SUAD}{\f0\fs16\cf1\cell}
\trowd
\trleft12
\clcbpat2\clbrdrt\brdrs\brdrw20\brdrcf1
\cellx1938
\clcbpat2\clbrdrt\brdrs\brdrw20\brdrcf1
\cellx9756
\clcbpat2\clbrdrt\brdrs\brdrw20\brdrcf1
\cellx11840
\row
\pard\itap0\qc\sl259\slmult1\sa160\lin120\rin120\tqc\tx4788\tqr\tx9468 {\f0\fs16\cf1 Page }{\f0\fs16\cf1 \chpgn}{\f0\fs16\cf1  of }{\f0\fs16\cf1 {\field{\*\fldinst NUMPAGES}{\fldrslt 1}}}
{\f0\fs16\cf1\par}
\pard\itap0\sl-207\slmult0\lin239\rin230 {\f0\fs20\cf1\par}
}
\pard\itap0\sl240\slmult0\lin120\rin120\cbpat2 {\f0\fs14\cf1\highlight2\par}
\trowd
\trqc
\trleft325
\clvertalc\clcbpat2\clbrdrt\brdrs\brdrw20\brdrcf1\clbrdrl\brdrs\brdrw20\brdrcf1\clbrdrr\brdrs\brdrw60\brdrcf1
\cellx10740
\pard\intbl\qc\sl240\slmult0\lin108\rin108 {\f0\fs20\b\i\cf1 Account: }{\f0\fs20\b\i\cf1 3000001102010}{\f0\fs20\b\i\cf1     Agency: }{\f0\fs20\b\i\cf1 ALL}{\f0\fs20\b\i\cf1     Location: }{\f0\fs20\b\i\cf1 ALL}{\f0\fs20\b\i\cf1     Trouble Code: }{\f0\fs20\b\i\cf1 ALL}{\f0\fs20\b\i\cf1\cell}
\trowd
\trqc
\trleft325
\clvertalc\clcbpat2\clbrdrt\brdrs\brdrw20\brdrcf1\clbrdrl\brdrs\brdrw20\brdrcf1\clbrdrr\brdrs\brdrw60\brdrcf1
\cellx10740
\row
\trowd
\trqc
\trleft325
\clvertalc\clcbpat2\clbrdrb\brdrs\brdrw60\brdrcf1\clbrdrl\brdrs\brdrw20\brdrcf1\clbrdrr\brdrs\brdrw60\brdrcf1
\cellx10740
\pard\intbl\qc\sl240\slmult0\lin108\rin108 {\f0\fs20\b\i\cf1 Close Date Start: 02/04/2020    Close Date End: 02/11/2020    Detail: N}{\f0\fs20\b\i\cf1\cell}
\trowd
\trqc
\trleft325
\clvertalc\clcbpat2\clbrdrb\brdrs\brdrw60\brdrcf1\clbrdrl\brdrs\brdrw20\brdrcf1\clbrdrr\brdrs\brdrw60\brdrcf1
\cellx10740
\row
\pard\itap0\sl240\slmult0\lin120\rin120\cbpat2 {\f0\fs20\cf1\highlight2\par}
\pard\itap0\sl240\slmult0\lin120\rin120\cbpat2 {\f0\fs16\cf1\highlight2\par}
\pard\itap0\sl240\slmult0\lin120\rin120\cbpat2 {\f0\fs22\b\cf3\highlight2 There\u160?are\u160?no\u160?records\u160?for\u160?these\u160?parameters...}{\f0\fs22\b\cf3\highlight2\par}
\pard\itap0\sl-281\slmult0\lin120\rin230\tqr\tx10296\tqr\tx11016 {\*\bkmkstart page_total_master0}{\*\bkmkend page_total_master0}{\*\bkmkstart page_total}{\*\bkmkend page_total}{\f0\fs20\cf1\par}
}

--B
`;
  extension = 'rtf';
	console.log("extension   "+extension);
	console.log("data   "+data);
    var exportedFilenmae = 'report.doc';
    console.log("exportedFilenmae   "+exportedFilenmae);
    var mimeType;
    if(extension ==='pdf'){
    mimeType = {type:'application/pdf'}
    } else if (extension === 'rtf'){
     mimeType = {type:'application/vnd.ms-word;charset=utf-8'}
    }
     else if (extension === 'csv'){
     mimeType = {type:'text/csv;charset=utf-8'}
    }else if (extension === 'xlsx'){
     mimeType = {type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'}
    }
    //{
  //  type: 'text/'+extension+';charset=utf-8;'
  //}
  //var blob = new Blob([data], mimeType);
  var blob = new File([data], "name.pdf");

  if (navigator.msSaveBlob) {
    // IE 10+
    navigator.msSaveBlob(blob, exportedFilenmae);
  } else {
    var link = document.createElement("a");
    if (link.download !== undefined) {

      var url = URL.createObjectURL(blob);
      link.setAttribute("href", url);
      link.setAttribute("download", exportedFilenmae);
      link.style.visibility = "hidden";
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
    }
  }


	})()